name: Notify Teams
description: Sends a notification to Microsoft Teams with build status and version information.

inputs:
  overall-status:
    description: 'Overall status of the build (success or failure)'
    required: true
  run-url:
    description: 'URL to the GitHub Actions run'
    required: true
  action-name:
    description: 'Name of the job or action'
    required: true
  workflow-status:
    description: 'Status of the workflow'
    required: true
  workflow-name:
    description: 'Name of the workflow'
    required: true
  version-info:
    description: 'Version information to display, newline-separated'
    required: true

runs:
  using: "composite"
  steps:
    - name: Send Notification
      shell: bash
      run: |
        WEBHOOK_URL="https://amdcloud.webhook.office.com/webhookb2/..."

        # Escape potential special characters and handle empty version-info
        version_info=$(echo "${{ inputs.version-info }}" | sed 's/^[ \t]*//;s/[ \t]*$//')
        if [[ -z "$version_info" ]]; then
          version_info="No version information available."
        fi

        # Prepare a list of unique version info while ensuring no duplicates for aianalyzer
        unique_versions=$(echo -e "$version_info" | sort -u | sed '/^$/d; s/^/• /')

        # Ensure AI Analyzer version is included only once, if it's not already
        if ! echo "$unique_versions" | grep -q "• aianalyzer"; then
          unique_versions="• aianalyzer 1.3.0.dev202410102250+g33080a\n$unique_versions"
        fi

        # Prepare Teams notification message based on overall status
        color="Good"
        if [[ "${{ inputs.overall-status }}" == "failure" ]]; then
          color="Attention"
        fi

        # Send notification
        curl -H 'Content-Type: application/json' \
             -d '{
                  "type": "message",
                  "attachments": [
                    {
                      "contentType": "application/vnd.microsoft.card.adaptive",
                      "content": {
                        "type": "AdaptiveCard",
                        "version": "1.2",
                        "body": [
                          {
                            "type": "TextBlock",
                            "text": "**Workflow Name:** '"${{ inputs.workflow-name }}"'",
                            "color": "'"$color"'"
                          },
                          {
                            "type": "TextBlock",
                            "text": "**Workflow Status:** '"${{ inputs.workflow-status }}"'",
                            "color": "'"$color"'"
                          },
                          {
                            "type": "TextBlock",
                            "text": "**Version Information:**\n'"${unique_versions}"'",
                            "color": "'"$color"'"
                          }
                        ],
                        "msteams": {
                          "width": "Full"
                        },
                        "actions": [
                          {
                            "type": "Action.OpenUrl",
                            "title": "View Run",
                            "url": "'"${{ inputs.run-url }}"'"
                          }
                        ]
                      }
                    }
                  ]
                }' \
             "$WEBHOOK_URL"
