name: Build and Notify
description: Sends notification to Microsoft Teams after build completion

inputs:
  webhook-url:
    description: 'Microsoft Teams webhook URL'
    required: true
  packages-file:
    description: 'Path to the file containing pip package versions'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up environment
      run: |
        echo "Setting up the environment"
    
    - name: Read package versions
      id: read-packages
      run: |
        echo "Reading package versions from ${{ inputs.packages-file }}"
        notifications=$(grep -E '^(aianalyzer|device-essentials-phx|device-essentials-strx|flexml|flexml-metadata|microkernel-tiling|onnxruntime-vitisai|ryzen-ai|torch|torch-mlir|torchvision|vai-q-onnx|vaiml|vaitrace|vitis-aie-essentials|vitis_mllib|voe)' ${{ inputs.packages-file }} | sed 's/^/ /; s/$/\n/' | tr -d '\r')
        echo "Captured notifications:"
        echo -e "$notifications"

        # Prepare the adaptive card payload
        PACKAGE_VERSIONS=""
        while IFS= read -r line; do
          IFS=' ' read -r package version <<< "$line"
          PACKAGE_VERSIONS+=$(echo "
          {
            \"type\": \"ColumnSet\",
            \"columns\": [
              {
                \"type\": \"Column\",
                \"width\": \"stretch\",
                \"items\": [
                  {
                    \"type\": \"TextBlock\",
                    \"text\": \"$package\",
                    \"wrap\": true
                  }
                ]
              },
              {
                \"type\": \"Column\",
                \"width\": \"stretch\",
                \"items\": [
                  {
                    \"type\": \"TextBlock\",
                    \"text\": \"$version\",
                    \"wrap\": true
                  }
                ]
              }
            ]
          },")
        done <<< "$notifications"

        # Remove the trailing comma from PACKAGE_VERSIONS
        PACKAGE_VERSIONS=${PACKAGE_VERSIONS%,}

        # Construct the final payload
        RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        echo "::set-output name=payload::{
          \"type\": \"message\",
          \"attachments\": [{
            \"contentType\": \"application/vnd.microsoft.card.adaptive\",
            \"content\": {
              \"type\": \"AdaptiveCard\",
              \"version\": \"1.2\",
              \"body\": [
                {
                  \"type\": \"TextBlock\",
                  \"text\": \"**Workflow Name:** Build and Notify\",
                  \"wrap\": true
                },
                {
                  \"type\": \"TextBlock\",
                  \"text\": \"**Workflow Status:** success\",
                  \"wrap\": true
                },
                {
                  \"type\": \"TextBlock\",
                  \"text\": \"**Package Version Information:**\",
                  \"wrap\": true
                },
                {
                  \"type\": \"ColumnSet\",
                  \"columns\": [
                    {
                      \"type\": \"Column\",
                      \"width\": \"stretch\",
                      \"items\": [
                        {
                          \"type\": \"TextBlock\",
                          \"text\": \"Package\",
                          \"weight\": \"Bolder\"
                        }
                      ]
                    },
                    {
                      \"type\": \"Column\",
                      \"width\": \"stretch\",
                      \"items\": [
                        {
                          \"type\": \"TextBlock\",
                          \"text\": \"Version\",
                          \"weight\": \"Bolder\"
                        }
                      ]
                    }
                  ]
                },
                $PACKAGE_VERSIONS
              ],
              \"msteams\": {
                \"width\": \"Full\"
              },
              \"actions\": [{
                \"type\": \"Action.OpenUrl\",
                \"title\": \"View Run\",
                \"url\": \"$RUN_URL\"
              }]
            }
          }]
        }"
    
    - name: Send notification to Microsoft Teams
      run: |
        echo "Sending notification to Microsoft Teams"
        curl -H "Content-Type: application/json" -d "${{ steps.read-packages.outputs.payload }}" "${{ inputs.webhook-url }}"
